---
- name: fetch dotfiles repo
  git: repo=https://github.com/pmeinhardt/huckleberry.git dest={{ home }}/.dotfiles
  tags: dotfiles

- name: write git configuration
  template: src=gitconfig.local.j2 dest={{ home }}/.dotfiles/git/gitconfig.local.symlink
  tags: dotfiles

- name: symlink dotfiles
  shell: ./script/link chdir={{ home }}/.dotfiles
  tags: dotfiles
