---
- name: install setuptools
  apt: pkg=python-setuptools state=present
  become: yes
  tags: python

- name: install pip
  easy_install: name=pip state=present
  become: yes
  tags: python

- name: install virtualenv
  pip: name=virtualenv state=present
  become: yes
  tags: python
