---
- name: install media tools via apt
  apt: pkg={{ item }} state=present
  with_items:
    - libav-tools
    - mplayer
  become: yes
  tags: media-tools

- name: install media tools via pip
  pip: name={{ item }} state=present
  with_items:
    - youtube-dl
  become: yes
  tags: media-tools
