---
# This role contains common plays.

- name: update apt cache
  apt: update_cache=yes

- name: upgrade safe packages
  apt: upgrade=safe

# Basic tools

- name: ensure basic tools are installed
  apt: pkg={{ item }} state=present
  with_items:
    - git
    - htop
    - iftop
    - iotop
    - sudo
    - vim
  tags: tools
