---
- name: update apt cache
  apt: update_cache=yes
  become: yes

- name: upgrade safe packages
  apt: upgrade=safe
  become: yes

- name: install essential tools
  apt: pkg={{ item }} state=present
  with_items:
    - build-essential
    - curl
    - git
    - htop
    - iftop
    - iotop
    - sudo
    - vim
  become: yes
